saas.lo: /var/www/source/working/zep/saas/ext/saas.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/saas.c -o saas.lo 
kernel/main.lo: /var/www/source/working/zep/saas/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /var/www/source/working/zep/saas/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /var/www/source/working/zep/saas/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/exception.c -o kernel/exception.lo 
kernel/debug.lo: /var/www/source/working/zep/saas/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /var/www/source/working/zep/saas/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /var/www/source/working/zep/saas/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /var/www/source/working/zep/saas/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /var/www/source/working/zep/saas/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /var/www/source/working/zep/saas/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /var/www/source/working/zep/saas/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /var/www/source/working/zep/saas/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /var/www/source/working/zep/saas/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /var/www/source/working/zep/saas/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /var/www/source/working/zep/saas/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /var/www/source/working/zep/saas/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /var/www/source/working/zep/saas/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /var/www/source/working/zep/saas/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /var/www/source/working/zep/saas/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /var/www/source/working/zep/saas/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/kernel/exit.c -o kernel/exit.lo 
saas/cores/exceptions/licenceexception.lo: /var/www/source/working/zep/saas/ext/saas/cores/exceptions/licenceexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/saas/cores/exceptions/licenceexception.zep.c -o saas/cores/exceptions/licenceexception.lo 
saas/cores/exceptions/licenceexpiredexception.lo: /var/www/source/working/zep/saas/ext/saas/cores/exceptions/licenceexpiredexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/saas/cores/exceptions/licenceexpiredexception.zep.c -o saas/cores/exceptions/licenceexpiredexception.lo 
saas/cores/exceptions/licenceinvalidexception.lo: /var/www/source/working/zep/saas/ext/saas/cores/exceptions/licenceinvalidexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/saas/cores/exceptions/licenceinvalidexception.zep.c -o saas/cores/exceptions/licenceinvalidexception.lo 
saas/cores/index.lo: /var/www/source/working/zep/saas/ext/saas/cores/index.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/saas/cores/index.zep.c -o saas/cores/index.lo 
saas/cores/saassystem.lo: /var/www/source/working/zep/saas/ext/saas/cores/saassystem.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/saas/cores/saassystem.zep.c -o saas/cores/saassystem.lo 
saas/0__closure.lo: /var/www/source/working/zep/saas/ext/saas/0__closure.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/source/working/zep/saas/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/source/working/zep/saas/ext/saas/0__closure.zep.c -o saas/0__closure.lo 
$(phplibdir)/saas.la: ./saas.la
	$(LIBTOOL) --mode=install cp ./saas.la $(phplibdir)

./saas.la: $(shared_objects_saas) $(SAAS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_saas) $(SAAS_SHARED_LIBADD)

