<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOa4dsrn\LibraryDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOa4dsrn/LibraryDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOa4dsrn.legacy');

    return;
}

if (!\class_exists(LibraryDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOa4dsrn\LibraryDevDebugProjectContainer::class, LibraryDevDebugProjectContainer::class, false);
}

return new \ContainerOa4dsrn\LibraryDevDebugProjectContainer(array(
    'container.build_hash' => 'Oa4dsrn',
    'container.build_id' => '34080d5a',
    'container.build_time' => 1550028590,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOa4dsrn');
