<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Zephir\BaseBackend' shared autowired service.

return $this->services['Zephir\BaseBackend'] = ${($_ = isset($this->services['Zephir\Backends\BackendFactory']) ? $this->services['Zephir\Backends\BackendFactory'] : ($this->services['Zephir\Backends\BackendFactory'] = new \Zephir\Backends\BackendFactory($this, '/root/zephir/kernels', '/root/zephir/templates'))) && false ?: '_'}->createBackend();
