<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Zephir\Config' shared autowired service.

return $this->services['Zephir\Config'] = \Zephir\Config::fromServer();
