<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'compiler_filesystem' shared service.

return $this->services['compiler_filesystem'] = new \League\Flysystem\Filesystem(new \League\Flysystem\Adapter\Local($this->targetDirs[0], 2, 2, array('file' => array('public' => 420, 'private' => 384), 'dir' => array('public' => 493, 'private' => 448))), array('visibility' => 'public', 'disable_asserts' => false));
