<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Zephir\FileSystem\FileSystemInterface' shared autowired service.

$this->services['Zephir\FileSystem\FileSystemInterface'] = $instance = new \Zephir\FileSystem\HardDisk(${($_ = isset($this->services['compiler_filesystem']) ? $this->services['compiler_filesystem'] : $this->load('getCompilerFilesystemService.php')) && false ?: '_'});

$instance->setBasePath($this->targetDirs[0]);

return $instance;
