<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'logger' shared service.

$this->services['logger'] = $instance = new \Symfony\Bridge\Monolog\Logger('app');

$instance->useMicrosecondTimestamps(true);
$instance->pushHandler(${($_ = isset($this->services['monolog.handler.console_stdout']) ? $this->services['monolog.handler.console_stdout'] : $this->load('getMonolog_Handler_ConsoleStdoutService.php')) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['monolog.handler.console_stderr']) ? $this->services['monolog.handler.console_stderr'] : $this->load('getMonolog_Handler_ConsoleStderrService.php')) && false ?: '_'});

return $instance;
