<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.handler.console_stdout' shared service.

$this->services['monolog.handler.console_stdout'] = $instance = new \Monolog\Handler\StreamHandler('php://stdout', 200, false, NULL);

$instance->pushProcessor(${($_ = isset($this->services['monolog.processor.psr_log_message']) ? $this->services['monolog.processor.psr_log_message'] : ($this->services['monolog.processor.psr_log_message'] = new \Monolog\Processor\PsrLogMessageProcessor())) && false ?: '_'});
$instance->setFormatter(${($_ = isset($this->services['compiler_log_formatter']) ? $this->services['compiler_log_formatter'] : $this->load('getCompilerLogFormatterService.php')) && false ?: '_'});

return $instance;
