<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_flysystem.plugin.list_files' shared service.

return $this->services['oneup_flysystem.plugin.list_files'] = new \League\Flysystem\Plugin\ListFiles();
