<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_flysystem.adapter_factory.awss3v2' shared service.

return $this->services['oneup_flysystem.adapter_factory.awss3v2'] = new \Oneup\FlysystemBundle\DependencyInjection\Factory\Adapter\AwsS3V2Factory();
