<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_flysystem.adapter_factory.webdav' shared service.

return $this->services['oneup_flysystem.adapter_factory.webdav'] = new \Oneup\FlysystemBundle\DependencyInjection\Factory\Adapter\WebDavFactory();
