<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_flysystem.cache_factory.stash' shared service.

return $this->services['oneup_flysystem.cache_factory.stash'] = new \Oneup\FlysystemBundle\DependencyInjection\Factory\Cache\StashFactory();
