<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_flysystem.cache_factory.psr6' shared service.

return $this->services['oneup_flysystem.cache_factory.psr6'] = new \Oneup\FlysystemBundle\DependencyInjection\Factory\Cache\Psr6Factory();
